In [10]:
import numpy as np # type: ignore
rng = np.random.default_rng(seed=1701) # seed for reproducibility
x1 = rng.integers(10, size=6) # one-dimensional array
x2 = rng.integers(10, size=(3, 4)) # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5)) # three-dimensional array

In [11]:
x1
x2
print(x3)
print(x3[1][3])

[[[4 3 5 5 0]
  [8 3 5 2 2]
  [1 8 8 5 3]
  [0 0 8 5 8]]

 [[5 1 6 2 3]
  [1 2 5 6 2]
  [5 2 7 9 3]
  [5 6 0 2 0]]

 [[2 9 4 3 9]
  [9 2 2 4 0]
  [0 3 0 0 2]
  [3 2 7 4 7]]]
[5 6 0 2 0]


In [12]:
my_array = rng.integers(1, 10, size = 5)
print(my_array)
my_array
empty_array = np.empty(3)
print(empty_array)
empty_array[1] = 6
print(empty_array)
print(empty_array[1])

[9 4 7 6 6]
[1.5e-323 2.0e-323 2.5e-323]
[1.5e-323 6.0e+000 2.5e-323]
6.0


In [13]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
values = rng.integers(1, 10, size=5)
compute_reciprocals(values)
%timeit compute_reciprocals(values)

12 μs ± 237 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [14]:
big_array = rng.integers(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

2.17 s ± 47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [15]:
print(1/big_array)
print(1.0 /big_array)
%timeit (1.0/big_array)

[0.01234568 0.04166667 0.02       ... 0.02083333 0.01086957 0.08333333]
[0.01234568 0.04166667 0.02       ... 0.02083333 0.01086957 0.08333333]
4.32 ms ± 380 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [16]:
print(compute_reciprocals(values))
print(1.0 / values)
%timeit (1.0 / values)

[1.         0.33333333 0.2        0.16666667 0.2       ]
[1.         0.33333333 0.2        0.16666667 0.2       ]
1.42 μs ± 25.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [17]:
%timeit compute_reciprocals(values)

11.7 μs ± 212 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [18]:
print(np.arange(5))
print(np.arange(1, 6))

[0 1 2 3 4]
[1 2 3 4 5]


In [19]:
print(np.arange(5) / np.arange(1, 6))
%timeit (np.arange(5) / np.arange(1, 6))

[0.         0.5        0.66666667 0.75       0.8       ]
3.67 μs ± 239 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [20]:
def simple_division(values1, values2):
    output = np.empty(len(values1))
    for i in range(len(values1)):
       output[i] = values1[i]/values2[i]
    return output
print(simple_division(np.arange(5), np.arange(1, 6)))
%timeit simple_division(np.arange(5), np.arange(1, 6))

[0.         0.5        0.66666667 0.75       0.8       ]
4.66 μs ± 168 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [21]:
x = np.arange(9)
y = x.reshape((3,3))

In [22]:
2 ** y

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [23]:
z = np.arange(4)
print("z = ", z)
print(1, 2)
print("z + 5 = ", z+5)

z =  [0 1 2 3]
1 2
z + 5 =  [5 6 7 8]


In [24]:
m = np.arange(10000000)
%timeit np.add(m , 5)

42.3 ms ± 5.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
m = np.arange(10000000)
%timeit m+5

40.2 ms ± 2.51 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [26]:
np.arange(-2, 3)

array([-2, -1,  0,  1,  2])

In [27]:
theta = np.linspace(0, np.pi, 3)
print(theta)

[0.         1.57079633 3.14159265]


In [28]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(1, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [1 1 1]


In [29]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [30]:
from scipy import special # type: ignore
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x) =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2) =", special.beta(x, 2))

gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2) = [0.5        0.03333333 0.00909091]


In [64]:
import scipy
print(scipy.__version__)


1.15.1


In [39]:
p = np.arange(1, 6)
np.add.reduce(p)

np.int64(15)

In [52]:
print(np.multiply.reduce(p))

120


In [54]:
print(np.multiply(p,p))

[ 1  4  9 16 25]


In [45]:
np.multiply.accumulate(p)
p

array([1, 2, 3, 4, 5])

In [56]:
print(np.sum(p))
print(p)

15
[1 2 3 4 5]


In [49]:
print(np.prod(p))

120


In [50]:
print(np.cumsum(p))

[ 1  3  6 10 15]


In [51]:
print(np.cumprod(p))

[  1   2   6  24 120]


In [71]:
x = np.arange(1000000)
# print(np.add.reduce(x))
%timeit np.add.reduce(x)

823 μs ± 130 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [72]:
# print(np.sum(x))
%timeit np.sum(x)

779 μs ± 54 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
