# <b>NumPy Array Attributs</b>

In [63]:
import numpy as np
rng = np.random.default_rng(seed=1701) # seed for reproducibility
x1 = rng.integers(10, size=6) # one-dimensional array
x2 = rng.integers(10, size=(3, 4)) # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5)) # three-dimensional array


In [64]:
import numpy as np
rng1 = np.random.default_rng(seed=0)
print(rng1.integers(10, size=6))  # Always produces the same numbers


[8 6 5 2 3 0]


In [65]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype: ", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:  int64


In [66]:
print(x3)
print(x3[-2][-1][-5])
print(x3[-2, -1, -5])
x3[-2, -1, -5] = 12.987
x1[0] = 3.134
print(x3[-2, -1])

[[[4 3 5 5 0]
  [8 3 5 2 2]
  [1 8 8 5 3]
  [0 0 8 5 8]]

 [[5 1 6 2 3]
  [1 2 5 6 2]
  [5 2 7 9 3]
  [5 6 0 2 0]]

 [[2 9 4 3 9]
  [9 2 2 4 0]
  [0 3 0 0 2]
  [3 2 7 4 7]]]
5
5
[12  6  0  2  0]


In [67]:
print(x3[0:2])

[[[ 4  3  5  5  0]
  [ 8  3  5  2  2]
  [ 1  8  8  5  3]
  [ 0  0  8  5  8]]

 [[ 5  1  6  2  3]
  [ 1  2  5  6  2]
  [ 5  2  7  9  3]
  [12  6  0  2  0]]]


In [68]:
x1[:]

array([3, 4, 0, 3, 8, 6])

In [69]:
my_list = [1, 2, 4]
print(my_list)
print(my_list[:2])
my_list

[1, 2, 4]
[1, 2]


[1, 2, 4]

In [70]:
initial_array = np.arange(1, 10)
grid = np.arange(1, 10).reshape(3, 3)
print(grid)
print(initial_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [71]:
initial_array = np.arange(1, 10)
initial_array.reshape(3, 3)
print(initial_array)


[1 2 3 4 5 6 7 8 9]


In [72]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [73]:
x = np.array([1, 2, 3])
x.reshape(3, 1)
# print(x.reshape(3, 1))

array([[1],
       [2],
       [3]])

In [74]:
np.array((1,2,3))

array([1, 2, 3])

In [75]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

In [76]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.concatenate([x, y]) #output:array([1, 2, 3, 3, 2, 1])
z[np.newaxis, :] #output: array([[1, 2, 3, 3, 2, 1]])
z[:, np.newaxis]

array([[1],
       [2],
       [3],
       [3],
       [2],
       [1]])

In [77]:
print(x3)
# x5 = np.dsplit(x3, [3])
# x5

[[[ 4  3  5  5  0]
  [ 8  3  5  2  2]
  [ 1  8  8  5  3]
  [ 0  0  8  5  8]]

 [[ 5  1  6  2  3]
  [ 1  2  5  6  2]
  [ 5  2  7  9  3]
  [12  6  0  2  0]]

 [[ 2  9  4  3  9]
  [ 9  2  2  4  0]
  [ 0  3  0  0  2]
  [ 3  2  7  4  7]]]


In [78]:
import sys

print(sys.implementation.name)


cpython
