In [42]:
import numpy as np
rng = np.random.default_rng()
L = rng.random(10000000)
# print(L)
print(np.sum(L))
%timeit np.sum(L)

5000023.889822487
20.7 ms ± 480 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [46]:
np.add.reduce(L)
%timeit np.add.reduce(L)

23.1 ms ± 3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [47]:
%timeit sum(L)
%timeit L.sum()
%timeit np.sum(L)

1.17 s ± 26.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
21.8 ms ± 314 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
21.2 ms ± 813 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [34]:
import numpy as np

x = np.array([[1, 2, 3], 
              [4, 5, 6],
              [9, 8, 7]])

print(np.sum(x, axis=1))  # Sum along axis 1 (rows)  #output: [ 6 15 24]
print(np.sum(x, axis=0))  #output: [14 15 16]


[ 6 15 24]
[14 15 16]


In [53]:
M = rng.integers(0, 10, (3, 4))
print(M)
MM= M.min(axis=0)
MM.shape

[[2 3 1 1]
 [8 3 1 8]
 [6 4 2 9]]


(4,)

In [54]:
MMM= M.max(axis=1)
MMM.shape

(3,)

In [56]:
#NaN-safe Function (np.nansum)
arr = np.array([1, 2, np.nan, 4, 5])
print("np.nansum(arr):", np.nansum(arr))  # ✅ Ignores NaN and sums remaining numbers
#output: np.nansum(arr): 12.0  # (1 + 2 + 4 + 5)

np.nansum(arr): 12.0


### <b>What Is the Average Height of US Presidents?</b> (in 'NumPyProjects' file)

In [71]:
import os
print(os.getcwd())  # Prints the current working directory


c:\PYTHON ELEMENTARY\DataScienceHandBook\Part2
