First: a simple example for each method that we learned in part 2 about methods and tools to access, set, and modify values in NumPy arrays.

In [428]:
import numpy as np

# ✅ 1. Using a loop with NumPy:
arr = np.array([[i + j for i in range(10, 70, 10)] for j in range(3)])
print(arr)
'''
Explanation:
    -range(10, 70, 10) generates [10, 20, 30, 40, 50, 60]
    -For each row (j from 0 to 2), we add j * 10 to each element
'''

# ✅ 2. Using NumPy broadcasting:
# base = np.array([10, 20, 30, 40, 50, 60])
# offsets = np.arange(3).reshape(3, 1)
# arr = base + offsets
# print(arr)
'''
How it works:
    -'base' is your row base: [10, 20, 30, 40, 50, 60] #(6,)
    -offsets is a column vector: [[0], [1], [2]] #(3,1)
    -Adding them together broadcasts the row across 3 rows with offsets.
'''

#✅ 3. Using np.tile to repeat a pattern:
# row = np.array([10, 20, 30, 40, 50, 60])
# arr = np.tile(row, (3, 1)) + np.arange(3).reshape(3, 1)
# print(arr)
'''
How it works:
    -np.tile(row, (3, 1)) repeats the base row 3 times
    -Then we add a column-wise offset: [0], [1], [2]
'''

[[10 20 30 40 50 60]
 [11 21 31 41 51 61]
 [12 22 32 42 52 62]]


'\nHow it works:\n    -np.tile(row, (3, 1)) repeats the base row 3 times\n    -Then we add a column-wise offset: [0], [1], [2]\n'

In [429]:
# 1. Indexing :Access a specific element using row and column indices.
arr[2, 1]  # → 22 (row 3, column 2)

22

In [430]:
# 2. Slicing: Access a range of elements. 
arr[:, 1:5]
#This selects all rows and columns 1 through 4 (not including column 5).

array([[20, 30, 40, 50],
       [21, 31, 41, 51],
       [22, 32, 42, 52]])

In [431]:
# 3. Masking (Boolean Indexing): Select elements based on a condition.
arr[arr > 50]

array([60, 51, 61, 52, 62])

In [432]:
# 4. Fancy Indexing (also called fancy slicing): Use lists or arrays of indices to access multiple arbitrary elements.
'''
In NumPy, fancy slicing (also called fancy indexing) refers to using arrays (or lists) of indices to access specific elements in another array. 
It's different from regular slicing (like arr[2:5]) because it lets you select non-contiguous elements or use boolean conditions.
'''
arr[0, [1, 5]]  # → Select column 1 and column 5 from row 0
# Output: array([20, 60])
arr[0, [1,2,5]] ## Output: array([20, 30, 60])

array([20, 30, 60])

In [433]:
# 5. Combinations of the above: Mix slicing with fancy indexing.
arr[:, [1, 5]]  # → All rows, columns 1 and 5

array([[20, 60],
       [21, 61],
       [22, 62]])

# <b>Chapter 14: Data Indexing and Selection</b>

## <b>Data Selection in Series</b>

In [434]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [435]:
'a' in data

True

In [436]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [437]:
type(data)

pandas.core.series.Series

In [438]:
set(data.items())

{('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)}

In [439]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [440]:
data['a'] = 90

In [441]:
data

a    90.00
b     0.50
c     0.75
d     1.00
dtype: float64

In [442]:
data['r'] = 90

In [443]:
data

a    90.00
b     0.50
c     0.75
d     1.00
r    90.00
dtype: float64

In [444]:
data['a':'d']

a    90.00
b     0.50
c     0.75
d     1.00
dtype: float64

In [445]:
data.index

Index(['a', 'b', 'c', 'd', 'r'], dtype='object')

In [446]:
data[(data>0.25) & (data<1.25)]

b    0.50
c    0.75
d    1.00
dtype: float64

In [447]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [448]:
data[3]

'b'

In [449]:
# data[2] #error
data.iloc[2] #'c'
data.loc[3] #'b'
# data.iloc[3] #single positional indexer is out-of-bounds

'b'

In [450]:
data[1:3]

3    b
5    c
dtype: object

In [451]:
data.loc[1:3] #Notice that when slicing with an explicit index (loc), the final index is included in the slice.

1    a
3    b
dtype: object

In [452]:
data.iloc[1:3] #Notice that when slicing with an implicit index (integer-location based or iloc), the final index is excluded from the slice.

3    b
5    c
dtype: object

In [453]:
data[:2] #it uses implicit Python-style indices

1    a
3    b
dtype: object

## <b>Data Selection in DataFrames</b>

In [454]:
area = pd.Series({'California': 423967, 'Texas': 695662,'New York': 141297, 'Florida': 170312,'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,'New York': 19651127, 'Florida': 19552860,'Illinois': 12882135})
data = pd.DataFrame({'areaaaa':area, 'popp':pop})
data

areaaaa      popp
California   423967  38332521
Texas        695662  26448193
New York     141297  19651127
Florida      170312  19552860
Illinois     149995  12882135

In [455]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [456]:
pop

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [457]:
# data['California'] #KeyError: 'California'
data['areaaaa']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: areaaaa, dtype: int64

In [458]:
data.areaaaa

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: areaaaa, dtype: int64

In [459]:
data.pop #این اون متد درونساخت دیتافریمز هست

<bound method DataFrame.pop of             areaaaa      popp
California   423967  38332521
Texas        695662  26448193
New York     141297  19651127
Florida      170312  19552860
Illinois     149995  12882135>

In [460]:
# data = pd.DataFrame({'areaaaa':area, 'pop':pop})
# data.pop is data["pop"]
#output: False

In [461]:
data.areaaaa is data['areaaaa']

True

In [462]:
data['density']=data['popp']/data['areaaaa']
data

areaaaa      popp     density
California   423967  38332521   90.413926
Texas        695662  26448193   38.018740
New York     141297  19651127  139.076746
Florida      170312  19552860  114.806121
Illinois     149995  12882135   85.883763

In [463]:
# data = pd.DataFrame({'areaaaa':area, 'pop':pop})  
# data['densityy']=data.pop/data.areaaaa 
# data
#output: error چون با متد پاپ درون ساخت دیتافریمز تداخل میکنه اون دیتادات پاپ

In [464]:
data['density']=data.popp/data.areaaaa 
data

areaaaa      popp     density
California   423967  38332521   90.413926
Texas        695662  26448193   38.018740
New York     141297  19651127  139.076746
Florida      170312  19552860  114.806121
Illinois     149995  12882135   85.883763

In [465]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [471]:
s = pd.Series({'a':2, 'b':4, 'c':9})
s

a    2
b    4
c    9
dtype: int64

In [472]:
s.values

array([2, 4, 9], dtype=int64)

In [473]:
s.index

Index(['a', 'b', 'c'], dtype='object')

In [474]:
s.T

a    2
b    4
c    9
dtype: int64

In [476]:
data.T

California         Texas      New York       Florida      Illinois
areaaaa  4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
popp     3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [489]:
data

areaaaa      popp     density
California   423967  38332521   90.413926
Texas        695662  26448193   38.018740
New York     141297  19651127  139.076746
Florida      170312  19552860  114.806121
Illinois     149995  12882135   85.883763

In [487]:
# data['California','areaaaa'] #KeyError: ('California', 'areaaaa')

In [488]:
data.loc['California','areaaaa'] #KeyError: 'California'

423967

In [490]:
data.iloc[0, 0]

423967

In [480]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [481]:
data.iloc[:3,:2]

areaaaa      popp
California   423967  38332521
Texas        695662  26448193
New York     141297  19651127

In [483]:
# data[:3,:2] #error

In [492]:
data.loc[:'Illinois', :'popp'] 

areaaaa      popp
California   423967  38332521
Texas        695662  26448193
New York     141297  19651127
Florida      170312  19552860
Illinois     149995  12882135

In [493]:
data.loc[data.density>100, ['popp','density']]

popp     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [494]:
data.iloc[0,2] = 90
data

areaaaa      popp     density
California   423967  38332521   90.000000
Texas        695662  26448193   38.018740
New York     141297  19651127  139.076746
Florida      170312  19552860  114.806121
Illinois     149995  12882135   85.883763

In [495]:
data[1:3]

areaaaa      popp     density
Texas      695662  26448193   38.018740
New York   141297  19651127  139.076746

In [502]:
# data[1,3] #KeyError: (1, 3)
data.iloc[1,2]

38.01874042279153

In [498]:
data['Texas':'New York']

areaaaa      popp     density
Texas      695662  26448193   38.018740
New York   141297  19651127  139.076746